# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: generic
sudo: false
os: osx

git:
  depth: 2

branches:
  only:
    - master
    - devel

matrix:
  fast_finish: true
  include:
    - env:
        - TOXENV=py27
    - env:
        - TOXENV=py35


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew update;
        if [[ "${TOXENV}" == "py27" ]]; then
            brew upgrade python;
            brew link --overwrite python
            pip2 install -U pip setuptools wheel pytest;
        else
            brew install python3;
            brew link --overwrite python3
            pip3 install -U pip setuptools wheel pytest;
        fi
    fi

# command to run tests
script:
  - python --version
  - pytest

notifications:
  email:
    on_success: never
    on_failure: never
