# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: generic
sudo: false
os: osx

git:
  depth: 2

branches:
  only:
    - master
    - devel

matrix:
  fast_finish: true
  include:
    - env:
        - TOXENV=py27
    - env:
        - TOXENV=py35


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        travis_retry brew update;
        if [[ "${TOXENV}" == "py27" ]]; then
            travis_retry brew install python;
        else
            travis_retry brew install python3;
        fi
    fi
  - python --version
  - travis_retry pip install -U pip setuptools wheel

install:
  - travis_retry pip install -U pytest
# command to run tests
script:
  - pytest

notifications:
  email:
    on_success: never
    on_failure: never
